export const FETCH_TICKETS_START = 'FETCH_TICKETS_START'
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS'
export const FETCH_TICKETS_ERROR = 'FETCH_TICKETS_ERROR'
export const FETCH_ID_START = 'FETCH_ID_START'
export const FETCH_ID_SUCCESS = 'FETCH_ID_SUCCESS'
export const FETCH_ID_ERROR = 'FETCH_ID_ERROR'

export const ACTIVE_CHECKBOX_ALL = 'ACTIVE_CHECKBOX_ALL'
export const ACTIVE_CHECKBOX_WITHOUT = 'ACTIVE_CHECKBOX_WITHOUT'
export const ACTIVE_CHECKBOX_ONE = 'ACTIVE_CHECKBOX_ONE'
export const ACTIVE_CHECKBOX_TWO = 'ACTIVE_CHECKBOX_TWO'
export const ACTIVE_CHECKBOX_THREE = 'ACTIVE_CHECKBOX_THREE'

export const ACTIVE_TAB_PRICE = 'ACTIVE_TAB_PRICE'
